name: Checks

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - '**/*.json'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - '**/*.json'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 5
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
      - name: Install Poetry
        run: pipx install poetry
      - name: Poetry install
        run: poetry install
      - name: Run tests
        run: poetry run pytest tests
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          badge-title: coverage
          create-new-comment: true